name: Document

on: [pull_request]

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Install virtual environment
      run: poetry install

    - name: Generate docstring docs
      run: poetry run pdoc -o docs malbench

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'github-action@github.com'
        if ! git diff --quiet; then
            gh pr checkout ${{ github.event.pull_request.number }}
            git add .
            git commit -m 'Documentation'
            git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}