name: Security Check

on: [pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Environment
      extends: ./.github/templates/environment.yml

    - name: Check for vulnerabilities
      run: poetry check