name: Unit Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Environment
      uses: ./.github/templates/environment.yml

    - name: Run tests and coverage
      run: poetry run coverage run -m unittest discover -s tests

    - name: Get coverage report
      run: poetry run coverage report --fail-under=80
