name: Unit Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Install virtual environment
      run: poetry install

    - name: Run tests and coverage
      run: poetry run coverage run -m unittest discover -s tests

    - name: Get coverage report
      run: poetry run coverage report --fail-under=80
